### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by anh-chu** [wywywywy/docker_stats_exporter#9]
I deployed this in a stack with Prometheus and Grafana. However, there is no data (and no error log either). I also used your Grafana dashboard template with no result.
Here is my docker-compose.yaml:
```dockerfile
version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/sil/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3030:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  docker-stats:
    image: wywywywy/docker_stats_exporter:latest
    container_name: docker_stats_exporter
    ports:
      - "9487:9487"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
``` 
and my prometheus.yaml:
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'docker_stats_exporter'
    metrics_path: /
    static_configs:
    - targets:
        - '127.0.0.1:9487'
```
